ALTER TABLE users ADD COLUMN address TEXT DEFAULT NULL AFTER phone;
ALTER TABLE users ADD COLUMN dob DATE DEFAULT NULL AFTER address;
ALTER TABLE users ADD COLUMN profile_photo VARCHAR(255) DEFAULT 'default.png' AFTER dob;
